USE CollectionDB;
GO

IF SCHEMA_ID(N'history') IS NULL	
	EXEC sp_executesql N'CREATE SCHEMA history AUTHORIZATION dbo;'
	GO

--ALTER TABLE data.ClassValues
--SET (SYSTEM_VERSIONING=OFF);
--GO

--DROP TABLE history.ClassValues;
--GO

IF OBJECT_ID(N'data.ClassValues', N'U') IS NOT NULL
	DROP TABLE data.ClassValues;
	GO

CREATE TABLE data.ClassValues
(
	Server_Id	UNIQUEIDENTIFIER	NOT NULL,
	Class_Id	UNIQUEIDENTIFIER	NOT NULL,
	PValue01	SQL_VARIANT			NOT NULL,
	PValue02	SQL_VARIANT			NULL,
	PValue03	SQL_VARIANT			NULL,
	PValue04	SQL_VARIANT			NULL,
	PValue05	SQL_VARIANT			NULL,
	PValue06	SQL_VARIANT			NULL,
	PValue07	SQL_VARIANT			NULL,
	PValue08	SQL_VARIANT			NULL,
	PValue09	SQL_VARIANT			NULL,
	PValue10	SQL_VARIANT			NULL,

	ValidFrom	DATETIME2(2) GENERATED ALWAYS AS ROW START NOT NULL,
	ValidTo		DATETIME2(2) GENERATED ALWAYS AS ROW END	NOT NULL,
	PERIOD FOR SYSTEM_TIME
	(
		ValidFrom,
		ValidTo
	),

	CONSTRAINT pk_ClassValues PRIMARY KEY CLUSTERED
	(
		Server_Id,
		Class_Id,
		PValue01
	)
)
WITH
(
	SYSTEM_VERSIONING = ON
	(HISTORY_TABLE = history.ClassValues)
)